// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuizService.Infrastructure.Data;

#nullable disable

namespace QuizService.Infrastructure.Migrations
{
    [DbContext(typeof(QuizDbContext))]
    [Migration("20260113153609_AddTwoNewValue")]
    partial class AddTwoNewValue
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuizService.Domain.Models.Quiz.Quiz", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("QuizId");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ExternalId");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuizStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Generating");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SourceId");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Quizzes", (string)null);
                });

            modelBuilder.Entity("QuizService.Domain.QuizAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("QuizAttemptId");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Difficult")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("QuizId");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<string>("SnapshotQuizJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SnapshotQuizJson");

                    b.Property<DateTime>("StartQuiz")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("QuizId")
                        .HasDatabaseName("IX_QuizAttempts_QuizId");

                    b.ToTable("QuizAttempts", (string)null);
                });

            modelBuilder.Entity("QuizService.Domain.ValuesObject.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TagId");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("QuizTag", b =>
                {
                    b.Property<Guid>("QuizId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("QuizId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("QuizTag", (string)null);
                });

            modelBuilder.Entity("QuizService.Domain.Models.Quiz.Quiz", b =>
                {
                    b.OwnsMany("QuizService.Domain.Models.Quiz.QuizQuestion", "Questions", b1 =>
                        {
                            b1.Property<Guid>("QuizId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("QuizId");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("QuizQuestionId");

                            b1.Property<DateTime?>("CreateTime")
                                .HasColumnType("datetime2");

                            b1.Property<string>("CreatedBy")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Explanation")
                                .HasMaxLength(2000)
                                .IsUnicode(true)
                                .HasColumnType("nvarchar(2000)");

                            b1.Property<DateTime?>("LastModified")
                                .HasColumnType("datetime2");

                            b1.Property<string>("LastModifiedBy")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<Guid?>("SourceChunkId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .IsUnicode(true)
                                .HasColumnType("nvarchar(1000)");

                            b1.HasKey("QuizId", "Id");

                            b1.ToTable("QuizQuestions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("QuizId");

                            b1.OwnsMany("QuizService.Domain.Models.Quiz.QuizAnswer", "Answers", b2 =>
                                {
                                    b2.Property<Guid>("QuizId")
                                        .HasColumnType("uniqueidentifier")
                                        .HasColumnName("QuizId");

                                    b2.Property<Guid>("QuizQuestionId")
                                        .HasColumnType("uniqueidentifier")
                                        .HasColumnName("QuizQuestionId");

                                    b2.Property<Guid>("Id")
                                        .HasColumnType("uniqueidentifier")
                                        .HasColumnName("QuizAnswerId");

                                    b2.Property<DateTime?>("CreateTime")
                                        .HasColumnType("datetime2");

                                    b2.Property<string>("CreatedBy")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<bool>("IsCorrect")
                                        .HasColumnType("bit");

                                    b2.Property<DateTime?>("LastModified")
                                        .HasColumnType("datetime2");

                                    b2.Property<string>("LastModifiedBy")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<int>("Ordinal")
                                        .HasColumnType("int");

                                    b2.Property<string>("Text")
                                        .IsRequired()
                                        .HasMaxLength(1000)
                                        .IsUnicode(true)
                                        .HasColumnType("nvarchar(1000)");

                                    b2.HasKey("QuizId", "QuizQuestionId", "Id");

                                    b2.ToTable("QuizAnswers", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("QuizId", "QuizQuestionId");
                                });

                            b1.Navigation("Answers");
                        });

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("QuizService.Domain.QuizAttempt", b =>
                {
                    b.OwnsMany("QuizService.Domain.Entities.QuizAttemptQuestion", "AttemptQuestions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("QuizAttemptQuestionId");

                            b1.Property<DateTime?>("CreateTime")
                                .HasColumnType("datetime2");

                            b1.Property<string>("CreatedBy")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool>("IsCorrect")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bit")
                                .HasDefaultValue(false);

                            b1.Property<DateTime?>("LastModified")
                                .HasColumnType("datetime2");

                            b1.Property<string>("LastModifiedBy")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<Guid>("QuizAttemptId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("QuizAttemptId");

                            b1.Property<Guid>("QuizQuestionId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("QuizQuestionId");

                            b1.Property<string>("_correctAnswerIds")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("CorrectAnswerIds");

                            b1.Property<string>("_selectedAnswerIds")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("SelectedAnswerIds");

                            b1.HasKey("Id");

                            b1.HasIndex("QuizQuestionId")
                                .HasDatabaseName("IX_QuizAttemptQuestions_QuizQuestionId");

                            b1.HasIndex("QuizAttemptId", "QuizQuestionId")
                                .IsUnique()
                                .HasDatabaseName("IX_QuizAttemptQuestions_Attempt_Question_UQ");

                            b1.ToTable("QuizAttemptQuestions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("QuizAttemptId");
                        });

                    b.Navigation("AttemptQuestions");
                });

            modelBuilder.Entity("QuizTag", b =>
                {
                    b.HasOne("QuizService.Domain.Models.Quiz.Quiz", null)
                        .WithMany()
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizService.Domain.ValuesObject.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
